### ISSUE TITLE
IE

### ISSUE THREAD

**Issue by SKsusha** [SKsusha/WEB#1]
- история возникновения
- особенности версий
- на базе чего создан
- поддерживаемые стандарты

**Comment by SergeyMirvoda** [comment]
Доклад должен быть не больше чем на 10минут.
Написан в html и приложен файлом к этой задаче.
Не позднее понедельника.

**Comment by SergeyMirvoda** [comment]
https://github.com/wshadw/Web-Developing/issues/1
